include:
  - remote: 'https://gitlab.com/devops108031/laboratory_work6.1/-/raw/dev/docker-build.yml'

stages:
  - build-deps
  - build-app

build-backend-deps:
  extends: .docker_build_template
  stage: build-deps
  variables:
    IMAGE_NAME: backend-deps
    BUILD_CONTEXT: ./backend
    DOCKERFILE_PATH: ./backend/Dockerfile
    TARGET_STAGE: deps
  rules:
    - changes:
        - backend/requirements.txt

build-backend-release:
  extends: .docker_build_template
  stage: build-app
  variables:
    IMAGE_NAME: backend
    BUILD_CONTEXT: ./backend
    DOCKERFILE_PATH: ./backend/Dockerfile
  rules:
    - changes:
        - backend/**/*.py

build-frontend-deps:
  extends: .docker_build_template
  stage: build-deps
  variables:
    IMAGE_NAME: frontend-deps
    BUILD_CONTEXT: ./frontend
    DOCKERFILE_PATH: ./frontend/Dockerfile
    TARGET_STAGE: deps
  rules:
    - changes:
        - frontend/package*.json

build-frontend-release:
  extends: .docker_build_template
  stage: build-app
  variables:
    IMAGE_NAME: frontend
    BUILD_CONTEXT: ./frontend
    DOCKERFILE_PATH: ./frontend/Dockerfile
  rules:
    - changes:
        - frontend/src/**/*
        - frontend/public/**/*