name: CI Pipeline

on:
  push:
    branches: [ main, master ]

permissions:
  contents: read
  packages: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend_deps: ${{ steps.filter.outputs.backend_deps }}
      backend_app: ${{ steps.filter.outputs.backend_app }}
      frontend_deps: ${{ steps.filter.outputs.frontend_deps }}
      frontend_app: ${{ steps.filter.outputs.frontend_app }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend_deps:
              - 'backend/requirements.txt'
              - 'backend/Dockerfile'
            backend_app:
              - 'backend/**/*.py'
              - 'backend/Dockerfile'
            frontend_deps:
              - 'frontend/package*.json'
              - 'frontend/Dockerfile'
            frontend_app:
              - 'frontend/src/**/*'
              - 'frontend/public/**/*'
              - 'frontend/Dockerfile'

  build-backend-deps:
    needs: changes
    if: ${{ needs.changes.outputs.backend_deps == 'true' }}
    uses: IRakuzanI/laboratory_work6.1/.github/workflows/docker-build.yml@main
    with:
      image_name: backend-deps
      build_context: ./backend
      dockerfile_path: ./backend/Dockerfile
      target_stage: deps

  build-backend-release:
    needs: changes
    if: ${{ needs.changes.outputs.backend_app == 'true' }}
    uses: IRakuzanI/laboratory_work6.1/.github/workflows/docker-build.yml@main
    with:
      image_name: backend
      build_context: ./backend
      dockerfile_path: ./backend/Dockerfile

  build-frontend-deps:
    needs: changes
    if: ${{ needs.changes.outputs.frontend_deps == 'true' }}
    uses: IRakuzanI/laboratory_work6.1/.github/workflows/docker-build.yml@main
    with:
      image_name: frontend-deps
      build_context: ./frontend
      dockerfile_path: ./frontend/Dockerfile
      target_stage: deps

  build-frontend-release:
    needs: changes
    if: ${{ needs.changes.outputs.frontend_app == 'true' }}
    uses: IRakuzanI/laboratory_work6.1/.github/workflows/docker-build.yml@main
    with:
      image_name: frontend
      build_context: ./frontend
      dockerfile_path: ./frontend/Dockerfile
      
